"""add title and type fields to notification table

Revision ID: 9baee67470d6
Revises: 7c0be1a58ba6
Create Date: 2025-04-14 00:18:27.391388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9baee67470d6'
down_revision = '7c0be1a58ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('related_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('solution_comment', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('related_id')
        batch_op.drop_column('type')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
